### ISSUE TITLE
Panic happened

### ISSUE THREAD

**Issue by roynwang** [ymatrix-data/mxbench#19]
Panic happened.

```
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] panic: invalid argument to Int63n
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] goroutine 16 [running]:
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] math/rand.(*Rand).Int63n(0x18?, 0x7f69b1874108?)
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper]         /opt/hostedtoolcache/go/1.19.8/x64/src/math/rand/rand.go:110 +0xe8
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] math/rand.Int63n(...)
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper]         /opt/hostedtoolcache/go/1.19.8/x64/src/math/rand/rand.go:327
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] [github.com/ymatrix-data/mxbench/internal/engine/metadata.(*Metadata).GetRandomVinsGenerator.func1()](http://github.com/ymatrix-data/mxbench/internal/engine/metadata.(*Metadata).GetRandomVinsGenerator.func1())
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper]         /home/runner/work/matrixdb-ci/matrixdb-ci/internal/engine/metadata/metadata.go:244 +0xa5
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] [github.com/ymatrix-data/mxbench/internal/engine/metadata.(*Metadata).GetSingleVinGenerator.func1()](http://github.com/ymatrix-data/mxbench/internal/engine/metadata.(*Metadata).GetSingleVinGenerator.func1())
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper]         /home/runner/work/matrixdb-ci/matrixdb-ci/internal/engine/metadata/metadata.go:236 +0x2d
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] [github.com/ymatrix-data/mxbench/internal/engine/benchmark/telematics.(*devicePredicate).GetStr](http://github.com/ymatrix-data/mxbench/internal/engine/benchmark/telematics.(*devicePredicate).GetStr)(0xc000182f20?, 0xc00020ac40?, 0x0?)
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper]         /home/runner/work/matrixdb-ci/matrixdb-ci/internal/engine/benchmark/telematics/query_combination_expr.go:91 +0x76
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] [github.com/ymatrix-data/mxbench/internal/engine/benchmark/telematics.(*queryCombination).GetSQL(0xc000066c00)](http://github.com/ymatrix-data/mxbench/internal/engine/benchmark/telematics.(*queryCombination).GetSQL(0xc000066c00))
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper]         /home/runner/work/matrixdb-ci/matrixdb-ci/internal/engine/benchmark/telematics/query_combination.go:50 +0x125
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] [github.com/ymatrix-data/mxbench/internal/engine.(*Engine).dumpBench](http://github.com/ymatrix-data/mxbench/internal/engine.(*Engine).dumpBench)(0xc0000c6d80, {0x380?, 0x7f69b1742fff?}, {0xb3bf00, 0xc000066c00}, {0xc000042580?, 0x41726b?})
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper]         /home/runner/work/matrixdb-ci/matrixdb-ci/internal/engine/engine.go:591 +0x56
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] [github.com/ymatrix-data/mxbench/internal/engine.(*Engine).execBench](http://github.com/ymatrix-data/mxbench/internal/engine.(*Engine).execBench)(0xc0000c6d80, {0xb3f6c8, 0xc0000a1080}, {0xb3bf00?, 0xc000066c00}, {0xb40ae0?, 0xc000000640?})
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper]         /home/runner/work/matrixdb-ci/matrixdb-ci/internal/engine/engine.go:522 +0x9b
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] [github.com/ymatrix-data/mxbench/internal/engine/benchmark/telematics.(*Benchmark).exec.func1()](http://github.com/ymatrix-data/mxbench/internal/engine/benchmark/telematics.(*Benchmark).exec.func1())
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper]         /home/runner/work/matrixdb-ci/matrixdb-ci/internal/engine/benchmark/telematics/telematics.go:173 +0x264
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper] created by [github.com/ymatrix-data/mxbench/internal/engine/benchmark/telematics.(*Benchmark).exec](http://github.com/ymatrix-data/mxbench/internal/engine/benchmark/telematics.(*Benchmark).exec)
2023-04-22:09:29:48.912 mxui:root:mdw:000208-[[34mINFO[0m]:-[cmdwrapper]         /home/runner/work/matrixdb-ci/matrixdb-ci/internal/engine/benchmark/telematics/telematics.go:169 +0x513
```

**Comment by roynwang** [comment]
录像1分22秒处。
在UI中先执行 写入测试， 完成后执行查询测试
https://user-images.githubusercontent.com/2215991/234747553-84e7942a-cae5-4792-aaa4-24a2c07b824c.mp4
